#!/bin/bash

if !(type rbenv > /dev/null 2>&1); then
  git clone https://github.com/rbenv/rbenv.git ${HOME}/.config/rbenv
  cd ${HOME}/.config/rbenv && src/configure && make -C src
  echo 'export RBENV_ROOT="$HOME/.config/rbenv"' >> ${HOME}/.bash_profile
  echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> ${HOME}/.bash_profile
  echo 'eval "$(rbenv init -)"' >> ${HOME}/.bash_profile
  ${HOME}/.config/rbenv/bin/rbenv init
fi

source ${HOME}/.bash_profile
rbenv install $(rbenv install -l | grep -v - | tail -1)
