#!/usr/bin/env bash

## turn off start up volume
sudo nvram SystemAudioVolume=%80

## remove all dock icons
defaults write com.apple.dock persistent-apps -array
killall Dock

## key repeat
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 1

## screen shot saved directory
defaults write com.apple.screencapture location ~/Downloads/;killall SystemUIServer

## reverse scroll
defaults write -g com.apple.swipescrolldirection -bool false
