#!/bin/bash

if !(type pyenv > /dev/null 2>&1); then
  git clone https://github.com/pyenv/pyenv.git ${HOME}/.config/pyenv
  echo 'export PYENV_ROOT="${HOME}/.config/pyenv"' >> ~/.bash_profile
  echo 'export PATH="${PYENV_ROOT}/bin:$PATH"' >> ~/.bash_profile
  echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile
  exec "$SHELL"
fi
