#!/usr/bin/env bash

## symbolic link files
mkdir -p ${HOME}/.config
curl -L https://github.com/panage/dotfiles/archive/master.tar.gz | tar zxv
mv -f ${HOME}/dotfiles-master ${HOME}/dotfiles

xcode-select --install

ln -fnsv ${HOME}/dotfiles/git ${HOME}/.config/git
ln -fnsv ${HOME}/dotfiles/scripts ${HOME}/.config/scripts
ln -fnsv ${HOME}/dotfiles/ssh ${HOME}/.ssh

chmod 700 ${HOME}/dotfiles/ssh
chmod 600 ${HOME}/dotfiles/ssh/config

## git-completion
curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash \
  -o ${HOME}/.config/scripts/git-completion.bash

## source
echo '' >> ${HOME}/.bash_profile
echo 'source ${HOME}/.config/scripts/git-completion.bash' >> ${HOME}/.bash_profile
echo "" >> ${HOME}/.bash_profile
echo 'source ${HOME}/.config/scripts/aliases' >> ${HOME}/.bash_profile
echo '' >> ${HOME}/.bash_profile
echo 'source ${HOME}/.config/scripts/functions' >> ${HOME}/.bash_profile

source ${HOME}/dotfiles/initial/install-sdkman
source ${HOME}/dotfiles/initial/install-pyenv

source ${HOME}/dotfiles/initial/install-brew
source ${HOME}/dotfiles/initial/install-goenv
source ${HOME}/dotfiles/initial/install-mac
ln -fnsv ${HOME}/dotfiles/Brewfile ${HOME}/.config/Brewfile
cd ${HOME}/.config && brew bundle
cd ${HOME}/dotfiles

ln -fnsv ${HOME}/dotfiles/Code/User/keybindings.json ${HOME}/Library/ApplicationSupport/Code/User/keybindings.json
ln -fnsv ${HOME}/dotfiles/Code/User/settings.json ${HOME}/Library/ApplicationSupport/Code/User/settings.json

echo '' >> ${HOME}/.bash_profile
echo 'export PATH=\"/usr/local/opt/gnu-sed/libexec/gnubin:$PATH\"' >> ${HOME}/.bash_profile
echo 'export PATH=\"/usr/local/opt/grep/libexec/gnubin:$PATH\"' >> ${HOME}/.bash_profile

exit 0

